name: Windows Build MSVC
on:
    push:
        branches: [development]
    pull_request:
        branches: [development]
env:
    build_type: "Release"
    cc: "cl"
    cxx: "cl"
    environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
    generators: "Visual Studio 17 2022"

concurrency:
    group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
    cancel-in-progress: true
jobs:
    build-windows:
        if: github.repository == 'TorqueGameEngines/Torque3D'
        name: Windows Latest MSVC
        runs-on: windows-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v3

            - name: Print env
              run: |
                echo github.event.action: ${{ github.event.action }}
                echo github.event_name: ${{ github.event_name }}

            - name: Setup MSVC problem matcher
              uses: ammaraskar/msvc-problem-matcher@master

            - name: Install Windows MSVC Dependencies
              run: |
                choco install cmake
                cmake --version
                cmd "${{env.environment_script}}"

            - name: Configure
              shell: bash
              run: cmake -B ${{github.workspace}}/build -G "${{env.generators}}" -DCMAKE_BUILD_TYPE=${{env.build_type}} -DTORQUE_APP_NAME=Torque3D -DTORQUE_TESTING=ON
            
            - name: Build
              shell: bash
              run: cmake --build . --config ${{ env.build_type}}

            - name: Install
              shell: bash
              run: cmake --install
                