name: MacOSX Build CLANG
on:
    push:
        branches: [development]
    pull_request:
        branches: [development]
env:
    build_type: "Release"
    cc: "clang"
    cxx: "clang++"

concurrency:
    group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macosx
    cancel-in-progress: true
jobs:
    build-linux:
        if: github.repository == 'TorqueGameEngines/Torque3D'
        name: MacOSX Latest CLANG
        runs-on: macos-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v3
            - name: Print env
              run: |
                echo github.event.action: ${{ github.event.action }}
                echo github.event_name: ${{ github.event_name }}

            - name: Install MacOSX Dependencies
              run: |
                cmake --version

            - name: Configure Build & Install
              uses: ashutoshvarma/action-cmake-build@v1
              with:
                build-dir: ${{github.workspace}}/build
                # will set the CC & CXX for cmake
                cc: ${{env.cc}}
                cxx: ${{env.cxx}}
                build-type: ${{env.build_type}} 
                # Extra options pass to cmake while configuring project
                configure-options: -DTORQUE_APP_NAME=Torque3D -DTORQUE_TESTING=ON
                # install the build using cmake --install
                install-build: true
                # run build using '-j [parallel]' to use multiple threads to build
                parallel: 14

            - name: Unit Tests
              shell: bash
              run: |
                cd "${{github.workspace}}/My Projects/Torque3D/game"
                ./Torque3D.app/Contents/MacOS/Torque3D runTests.tscript

            - name: Upload Artifact
              uses: ./.github/actions/upload-artifact
              with:
                name: torque3dMacOSXCLANGUnitTest