name: Report Test Results
on:
  workflow_run:
    workflows: [Windows Build, Linux Build, MacOSX Build]
    types:
      - completed

permissions:
    checks: write

jobs:
  checks:
    runs-on: ${{matrix.config.runos}}
    strategy:
        fail-fast: false
        matrix:
          config:
          - {
                name: "Windows Test Results",
                runos: windows-latest,
                artifact-name: "torque3dLinuxGCCUnitTest"
            }
          - {
              name: "Linux Test Results",
              artifact-name: "torque3dLinuxGCCUnitTest"
            }
          - {
                name: "Mac Test Results",
                artifact-name: "torque3dMacOSXCLANGUnitTest"
            }
    steps:
      - name: Publish ${{matrix.config.name}}
        uses: ./.github/actions/test-results
        with:
          artifact-name: ${{matrix.config.artifact-name}}
          name: ${{matrix.config.name}}

