name: Report Test Results
on:
  workflow_run:
    workflows: ["Linux Build"]
    types:
      - completed

permissions:
    checks: write

jobs:
    checks:
        name: ${{matrix.config.name}}
        runs-on: ${{matrix.config.runos}}
        strategy:
            fail-fast: false
            matrix:
              config: 
              - {
                  name: "Linux Test Results",
                  runos: ubuntu-latest,
                  artifact-name: "torque3dLinuxGCCUnitTest"
                }
              
        steps:
            - name: Test Reporter
              uses: phoenix-actions/test-reporting@v12
              with:
                artifact: ${{matrix.config.artifact-name}}
                name: ${{matrix.config.name}}
                path: "**/My Projects/Torque3D/game/test_detail.xml"
                reporter: java-junit 
